{% set version = "2026.01.21" %}

package:
  name: pangeo-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask =2026.1.1
    - distributed =2026.1.1
    - dask-gateway =2025.4.0

test:
  imports:
    - dask

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo dask dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq
    - jhamman
    - TomAugspurger
