{% set version = "2026.10.08" %}

package:
  name: pangeo-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask =2026.8.0
    - distributed =2026.8.0
    - dask-gateway =2026.3.0

test:
  imports:
    - dask

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo dask dependencies"

extra:
  recipe-maintainers:
    - jsignell
    - weiji14
    - yuvipanda
    - scottyhq
    - jhamman
    - TomAugspurger
