{% set version = "2021.08.15" %}

package:
  name: pangeo-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask =2021.8.0
    - distributed =2021.8.0
    - dask-kubernetes =2021.3.1
    - dask-gateway =0.9.0

test:
  imports:
    - dask

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo dask dependencies"

extra:
  recipe-maintainers:
    - scottyhq
    - jhamman
    - TomAugspurger
