{% set version = "2024.01.19" %}

package:
  name: pangeo-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask =2024.1.0
    - distributed =2024.1.0
    - dask-gateway =2024.1.0

test:
  imports:
    - dask

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo dask dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq
    - jhamman
    - TomAugspurger
