{% set version = "2023.04.29" %}

package:
  name: pangeo-dask
  version: {{ version }}

build:
  number: 1
  noarch: generic

requirements:
  run:
    - dask =2023.4.1
    - distributed =2023.4.1
    - dask-gateway =2023.1.1

test:
  imports:
    - dask

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo dask dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq
    - jhamman
    - TomAugspurger
